import os
from pymatgen.io.vasp.inputs import Potcar, Kpoints, Incar, Poscar, VaspInput
from monty.serialization import loadfn
from pymatgen.core.structure import Structure
from kgrid.series import cutoff_series
from kgrid import calc_kpt_tuple
from pymatgen.io.ase import AseAtomsAdaptor
import matplotlib.pyplot as plt
from pymatgen.ext.matproj import MPRester

def generate_kgrids_cutoffs(
    structure: Structure,
    kmin: int = 4,
    kmax: int = 20,
) -> list:
    """Generate a series of kgrids for your lattice between a real-space cutoff range of `kmin` and `kmax` (in A).
    For semiconductors, the default values (kmin: 4; kmax: 20) are generally good.
    For metals you might consider increasing a bit the cutoff (kmax~30).
    Returns a list of kmeshes.
    Args:
        atoms (ase.atoms.Atoms): _description_
        kmin (int, optional): _description_. Defaults to 4.
        kmax (int, optional): _description_. Defaults to 20.

    Returns:
        list: list of kgrids
    """
    # Transform struct to atoms
    aaa = AseAtomsAdaptor()
    atoms = aaa.get_atoms(structure=structure)
    # Calculate kgrid samples for the given material
    kpoint_cutoffs = cutoff_series(
        atoms=atoms,
        l_min=kmin,
        l_max=kmax,
    )
    kgrid_samples = [
        calc_kpt_tuple(atoms, cutoff_length=(cutoff - 1e-4))
        for cutoff in kpoint_cutoffs
    ]
    print(f"Kgrid samples: {kgrid_samples}")

    return kgrid_samples

def parse_encut(file_path):
    """Parse and plot the ENCUT convergence results from a file generated by vaspup2.0 `data-converge`."""
    # Read file content
    with open(file_path, "r") as f:
        encut_data = f.read()

    # Extract ENCUT values and energies per atom from the file content
    encut_values = [int(line.split()[0][1:]) for line in encut_data.split("\n") if line.strip() and not line.startswith("Directory")]
    encut_energies_per_atom = [float(line.split()[2]) for line in encut_data.split("\n") if line.strip() and not line.startswith("Directory")]

    # Plot the ENCUT convergence
    fig, ax = plt.subplots(figsize=(6, 5))
    ax.plot(encut_values, encut_energies_per_atom, marker="o", color="#D4447E", label="Energy per atom")

    # Draw convergence thresholds (±5 meV/atom and ±1 meV/atom) around the last energy value
    for threshold, color in zip([0.005, 0.001], ["#E9A66C", "#5FABA2"]):
        ax.hlines(
            y=encut_energies_per_atom[-1] + threshold,
            xmin=encut_values[0], xmax=encut_values[-1],
            color=color, linestyles="dashed", label=f"{1000*threshold:.1f} meV/atom"
        )
        ax.hlines(
            y=encut_energies_per_atom[-1] - threshold,
            xmin=encut_values[0], xmax=encut_values[-1],
            color=color, linestyles="dashed"
        )
        ax.fill_between(
            encut_values,
            encut_energies_per_atom[-1] - threshold,
            encut_energies_per_atom[-1] + threshold,
            color=color, alpha=0.1
        )

    # Set axis labels and legend
    ax.set_xlabel("ENCUT (eV)")
    ax.set_ylabel("Energy per atom (eV)")
    ax.legend(frameon=True)
    return fig

def parse_kpoints(file_path):
    """Parse and plot KPOINTS convergence results from a file generated by vaspup2.0."""
    # Read file content
    with open(file_path, "r") as f:
        kpoints_data = f.read()

    # Extract energy per atom and KPOINTS values
    kpoints_energies_per_atom = [float(line.split()[2]) for line in kpoints_data.split("\n")[1:] if line.strip()]
    
    # Extract KPOINTS values as formatted strings (e.g., '4x4x4')
    kpoints_values = [
        "x".join(line.split()[0].split("k")[-1].replace("_", "").split(","))
        for line in kpoints_data.split("\n")[1:] if line.strip()
    ]

    # Plot the KPOINTS convergence
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(kpoints_values, kpoints_energies_per_atom, marker="o", color="#D4447E", label="Energy per atom")

    # Draw convergence thresholds (±5 meV/atom and ±1 meV/atom) around the last energy value
    for threshold, color in zip([0.005, 0.001], ["#E9A66C", "#5FABA2"]):
        ax.hlines(
            y=kpoints_energies_per_atom[-1] + threshold,
            xmin=0, xmax=len(kpoints_values) - 1,
            color=color, linestyles="dashed", label=f"{1000 * threshold:.1f} meV/atom"
        )
        ax.hlines(
            y=kpoints_energies_per_atom[-1] - threshold,
            xmin=0, xmax=len(kpoints_values) - 1,
            color=color, linestyles="dashed"
        )
        ax.fill_between(
            range(len(kpoints_values)),
            kpoints_energies_per_atom[-1] - threshold,
            kpoints_energies_per_atom[-1] + threshold,
            color=color, alpha=0.1
        )

    # Set axis labels and rotate x-ticks
    ax.set_xlabel("KPOINTS")
    ax.set_ylabel("Energy per atom (eV)")
    ax.set_xticks(range(len(kpoints_values)))
    ax.set_xticklabels(kpoints_values, rotation=90)
    ax.legend(frameon=True)
    plt.tight_layout()
    return fig

with MPRester() as mpr:
    entries = mpr.get_entries("La2NiO4",inc_structure="final")
    entry = sorted(entries, key=lambda x: x.energy_per_atom)[0]
print(entry)

# Load the structure from the POSCAR file
try:
    prim_struc = entry.structure
    poscar = Poscar(prim_struc)
    prim_struc.to("prim_struc_POSCAR")

except FileNotFoundError:
    raise FileNotFoundError("POSCAR file 'LNO_Bulk_Primitive_POSCAR' not found.")
poscar = Poscar(prim_struc)


# Load pseudopotentials from YAML file
potcar_yaml = "/home/soki/doped/doped/VASP_sets/PotcarSet.yaml"
try:
    potcar_dict = loadfn(potcar_yaml)
except FileNotFoundError:
    raise FileNotFoundError(f"YAML file not found at {potcar_yaml}")
except Exception as e:
    raise ValueError(f"Error loading YAML file: {e}")

kgrids = generate_kgrids_cutoffs(prim_struc)
# Avoid duplicates
kgrids = list(set(kgrids))
# Sort
kgrids.sort()

# Mid entry of kpoints for the ENCUT convergence test
mid_kgrid = kgrids[len(kgrids)//2]
# And KPOITNS
kpoints = Kpoints(kpts=(mid_kgrid,))

# As string, to copy to vaspup2.0 CONFIG file
kpoints_string = ""
for k in kgrids:
    kpoints_string += f"{k[0]} {k[1]} {k[2]},"
kpoints_string

# Collect POTCAR names based on elements in the structure
potcar_names = []
print("Default PBE pseudopotentials:")
for el in prim_struc.composition.elements:
    element_name = str(el)
    if element_name not in potcar_dict["POTCAR"]:
        raise KeyError(f"No pseudopotential found for element {element_name} in the YAML file.")
    pseudopotential = potcar_dict["POTCAR"][element_name]
    print(f"Element {element_name}: {pseudopotential}")
    potcar_names.append(pseudopotential)

# Create the output directory if it doesn't exist
output_dir = "input/"
os.makedirs(output_dir, exist_ok=True)

# Create and write the POTCAR file
potcar = Potcar(symbols=potcar_names, functional="PBE")
potcar.write_file(os.path.join(output_dir, "POTCAR"))

# Incar file for convergence
incar_convergence = Incar.from_dict(
    {
        'ALGO': 'All',
        'EDIFF': 1e-07,
        'ENCUT': 450,
        'GGA': 'Pe',
        'IBRION': -1,
        'ISMEAR': 0,
        'ISPIN': 2,
        'LORBIT': 11,
        'LREAL': False,
        'NEDOS': 2000,
        'NELM': 100,
        'NSW': 0,
        'PREC': 'Accurate',
        'SIGMA': 0.05,
        'KPAR': 2,
        'NCORE': 8,
    }
)

vasp_input = VaspInput(poscar=poscar, incar=incar_convergence, kpoints=kpoints, potcar=potcar)
# Write to Bulk_convergence
vasp_input.write_input("input")


config=f"""# vaspup2.0 - Seán Kavanagh (sean.kavanagh.19@ucl.ac.uk), 2023
# This is the default config for automating convergence.
# Works for ground-state energy convergence and DFPT convergence.

conv_encut="1"		# 1 for ON, 0 for OFF (ENCUT Convergence Testing)
encut_start="300"	# Value to start ENCUT calcs from.
encut_end="900"		# Value to end ENCUT calcs on.
encut_step="50"		# ENCUT increment.

conv_kpoint="1"		# 1 for ON, 0 for OFF (KPOINTS Convergence Testing)
kpoints="{kpoints_string}" # All the kpoints meshes
# you want to try, separated by a comma

run_vasp="1"		# Run VASP after generating the files? (1 for ON, 0 for OFF)
#name="Bulk_Convergence" # Optional name to append to each jobname (remove "#")
"""
# Save it to input directory
with open("input/CONFIG", "w") as f:
    f.write(config)
 
##Specify the path to the Convergence_Data file
#file_path = "kpoint_converge/Convergence_Data"
#file_path1 = "../../cutoff_converge/Convergence_Data"
## Generate and display the plot
#fig = parse_kpoints(file_path)
#plt.savefig("kpoint_converge/Converge_kpoints.png",bbox_inches = 'tight')
#
#fig1 = parse_encut(file_path1)
#plt.savefig("../../cutoff_converge/Converge_encut.png",bbox_inches = 'tight')


